packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  sharp: true
  '@prisma/engines': true
  '@prisma/client': true
  prisma: true
  esbuild: true
  '@prisma/ppg': true
  '@scarf/scarf': true

overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
